= Babun - a windows shell you will love
:awestruct-layout: base
:homepage: http://babun.github.io
:download-link: http://babun.github.io
:github-repo: https://github.com/babun/babun
:github-issues: https://github.com/babun/babun/issues
pronounced "Baboon"

Babun is an open source, bundeled and tweaked Cygwin based tool with an apt-get-like package manager. It gives you a real shell experience on the Windows OS. 
Download the dist file from {download-link}[TODO], unzip it and run the install.bat script. Thats it. Your new beautiful windows shell is ready to use.

== Who should use it
* Mac's or Linux's users who have to work on a Windows machine
* Users with limited or no admin rights
* Windows users who are looking for a powerful console
* Cygwin users
* Everybody who needs or wants to have a really cool shell on windows

== Features
* Automatic, silent command-line installer
* Installation on Windows machine with no admin rights
* Pact - apt-get-like package manager
* xTerm-256 compatible console
* Native HTTP proxying support
* Pluggable architecture
* Preconfigured git and other development tools
* Integrated .oh-my-zsh
* Auto update

== Getting started
=== Installation
Download the dist file from TODO, unzip it and run the install.bat script. After a few minutes babun starts automatically.
The application will be installed in the %USER_HOME%\.babun directory.

=== Setting up proxy
To setup proxy edit the following lines in the .babunrc file (%USER_HOME%\.babun\cygwin\home\USER\.babunrc)
----
# Uncomment this lines to set up your proxy
# export http_proxy=http://user:password@server:port
# export https_proxy=$http_proxy
# export ftp_proxy=$http_proxy
# export no_proxy=localhost
----

=== Installing new packages
Babun uses the cygwin repository for installing tools. It has lots of ready to use tools installed. If you however did not find the tool that you need you can download it using the *pact* package manager:
----
{ ~ } » pact install arj                                                                     ~ 1
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache

Installing arj
Found package arj
--2014-03-30 19:34:38--  http://mirrors.kernel.org/sourceware/cygwin//x86/release/arj/arj-3.10.22-1.tar.bz2
Resolving mirrors.kernel.org (mirrors.kernel.org)... 149.20.20.135, 149.20.4.71, 2001:4f8:1:10:0:1994:3:14, ...
Connecting to mirrors.kernel.org (mirrors.kernel.org)|149.20.20.135|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 189944 (185K) [application/x-bzip2]
Saving to: `arj-3.10.22-1.tar.bz2'

100%[==========================================================>] 189,944      193K/s   in 1.0s

2014-03-30 19:34:39 (193 KB/s) - `arj-3.10.22-1.tar.bz2' saved [189944/189944]

Unpacking...
Package arj installed
----

=== Git
Babun comes with installed and pre-configured git. The only thing you should do is to add your name and email to git config. 
To do that execute the following commands in the babun shell:
----
git config --global user.name "your name"
git config --global user.email "your@email.com"
----

=== .oh-my-zsh
Babun is integrated with .oh-my-zsh. The zsh shell is the default shell after installation. You can still change to bash if you wish.
TODO - explain how to setup default shell

== Auto update
Babun checks every time on start up it if a new version is available. You can also enforce it by typing:
----
babun check
----

To update babun to a newest version type:
----
babun update
----
Please note that your local configuration files will not be overwritten during update. 

== Plugins
TODO

== Contributing
There are many ways to contribute:

* Use it and tell us what you think
* Recommend it to your friends
* Submit a {github-issues}[feature request] or a {github-issues}[bug report]
* Fork it on {github-repo}[github] and submit pull request

