
= Scenarios for Acceptance Test (Babun rel 1.1.0)

:numbered:

== Update your existing babun instance to 1.1.0

*Before you start testing please zip your current babun instance for backup!*

- Open babun
- Execute babun check to check if your internet connection works
- Run 'test_setup_script.sh' script in babun like this: (!)

----
wget http://static.reficio.org/babun/babun-betatest-setup.sh

dos2unix test_setup_script.sh

chmod 755 test_setup_script.sh

./test_setup_script.sh

source ~/.babunrc
----

- Execute 'babun update'

=== Verify installation

- babun update was invoked
- babun realized that the cygwin version is out of date and started cygwin update process closing itself
- cygwin update ended successfully
- babun window popped up at the end of the installation process

Execute steps described in <<verify, Verification after installation>>

== Fresh install 1.1.0 to user home

- download babun 1.1.0 candidate from http://static.reficio.org/babun/babun-1.1.0-candidate-dist.zip (please do not redistribute this file!)
- install babun (execute 'install.bat')
- execute 'babun check' (enter proxy in '~/.babunrc' if necessary)

=== Verify installation

- The installation ended successfully and babun window popped up at the end of the installation process

Execute steps described in <<verify, Verification after installation>>

== Fresh install 1.1.0 to folder with space

- download babun 1.1.0 candidate from http://static.reficio.org/babun/babun-1.1.0-candidate-dist.zip (please do not redistribute this file!)
- install babun to any folder with space (for example execute 'install.bat /t "d:/babun rocks"')
- execute 'babun check' (enter proxy in '~/.babunrc' if necessary)


=== Verify installation

- The installation ended successfully and babun window popped up at the end of the installation process

Execute steps described in <<verify, Verification after installation>>

[[verify]]
== Verification after installation

*A*

----
ls -l /
----

expected: you should see symlinks to all your drives, like

----
...
lrwxrwxrwx   1 rock star Domain Users     11 Mar 30 20:37 c -> /cygdrive/c
...
----

*B*

----
babun --version
---- 

expected: should see 1.1.0

*C*

----
babun update
----

expected: should see 

----
Executing babun update
  upstream  [master]
  installed [1.1.0]
  newest    [1.1.0]
Babun is up to date
Checking Cygwin version:
  installed [1.7.35]
  newest    [1.7.35]
Cygwin is up to date
----

*D*

----
 echo "abcd" | grep "a" 
----

should see 

----
abcd
----

should NOT see grep warnings

----
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
abcd
----

*E*

----
pact install ruby tmux
----

expected: ruby and tmux are installed correctly

----
ruby --version (prints ruby's version)
tmux (starts tmux. type 'exit' to exit)
----

*F*

----
pact update arj
arj --version
----

expected: arj is installed and prints it's version

*G*

---- 
pact install arj
----

expected: pact informs that arj is already installed

*H* 

----
pact remove arj
arj --version
----

expected: command not found: arj

*I*

----
open .
open www.gmail.com
----

expected: should open windows explorer, should open web browser

*J*

Execute your daily tasks to see if everything works for you!!

== Feedback

Once you completed all the tests please let us know

- if you are behind proxy or not
- on which OS you have tested
- send us the output if the test fails
- let us know also if all tests pass

You can post your feedback directly to https://github.com/babun/babun/issues/266

