
=== Babun 1.0.1 is out (06.06.2014)

Babun 1.0.1 is out! 

There's a lot of goodies that have been included in this release - the most importants ones are:

* There is no interference with the existing Cygwin installations.
* You may have whicespace or accent characters in your Windows username.
* You may install to a custom folder using the install.bat /t "d:\babun_folder" switch.
* You may install babun having the %HOME% env variable set (babun will reuse the user's Windows home folder)
* You can easily pin babun to taskbar

If you already have babun 1.0.0 just invoke "babun update" and enjoy the newest version!

We would like to thank the community for being very active and supportive. Special thanks to Babun's contributors:

austingreco https://github.com/babun/babun/pull/75[#75],
SamMorrowDrums https://github.com/babun/babun/pull/85[#85],
meeech https://github.com/babun/babun/pull/85[#85],
olivierdagenais https://github.com/babun/babun/pull/91[#91],
simonbasle https://github.com/babun/babun/pull/103[#103],
jsevol https://github.com/babun/babun/pull/108[#108] https://github.com/babun/babun/pull/110[#110],
prabirshrestha https://github.com/babun/babun/pull/129[#129],
dogrizz https://github.com/babun/babun/pull/138[#138],
mmounirou https://github.com/babun/babun/pull/153[#153] https://github.com/babun/babun/pull/156[#156],
bentsai https://github.com/babun/babun/pull/162[#162],
jktravis,
bitdeli-chef