
=== Babun 1.1.0 released (04.04.2015)

After months of hard work a new version of Babun has been finally promoted to production! 

This release features an important change in the auto-update behavior.

From now on +babun update+  will also check and update the underlying Cygwin instance with all Cygwin packages that have been already installed, apart from updating babun itself.

The main reason for this change was to make sure that the packages installed with +pact+ are compatible with the underlying Cygwin instance. Pact always fetches the newest available package from the Cygwin repository, but it does not update Cygwin's internal DLLs', thus it was possible that a new version of given package like git, ruby, emacs etc. would not work on top of the older Cygwin version embedded in babun.

For this reason it is important to keep pact packages and Cygwin core libraries 'in sync'.

Babun will automatically check on startup if there is a newer Cygwin version available and prompt the user to update it. 
On Cygwin update babun will close itself, run the Cygwin installer in a separate cmd process and restart itself once the installation has been completed.
If there is a newer version of Cygwin available pact will not allow the user to install new packages. Instead they will be prompted with the following message:

----
{ ~ }  » pact install arj                                                                       ~
-------------------------------------------------------------------------------
CRITICAL: The underlying Cygwin version is outdated!
It's forbidden to install new packages as they may fail to work.
Execute 'babun update' and follow the instructions to update Cygwin.
If you know what you are doing add '--force' flag to proceed.
-------------------------------------------------------------------------------
----

As you can see it is still possible to install packages using the +--force+ option but it is not guaranteed that the downloaded package will work correctly.

Big thanks to https://github.com/v-yadli[@v-yadli] for helping us designing and developing the concept of this feature.


The auto-update improvement is not the only change in 1.1.0. This release is shipped with other new features coded up during several hackergartens, hacking sessions and long coding nights. The most important features are:

* 'pact update', so that you may update a package to a newer version
* 'fake sudo', so that you can run scripts containg sudo 
* soft links to harddrives, like /c, /d, so that you may forget about /cygdrive/c
* a lot of fixed bugs; all of them are listed here: https://github.com/babun/babun/issues/266


Many thanks to everybody who contributed to this release via pull requests, by helping other users, or even by fixing typos!

Also a big thank you to https://github.com/almorelle[@almorelle], https://github.com/vanushv[@vanushv], https://github.com/tonilampela[@tonilampela], https://github.com/v-yadli[@v-yadli], https://github.com/harijoe[@harijoe], https://github.com/airborn[@airborn] and https://github.com/kubamarchwicki[@kubamarchwicki] for taking time and effort of testing the this version.

In case you have the previous version installed it's important to invoke 'babun update' to stay up-to-date!

We really hope that you'll like this release. If you do, tweet about it, star babun on github or just... enjoy it :)

Cheers

@lukaszpielak, @tombujok

P.S. If somebody is interested in the full list of issues that have been squashed in 1.1.0, just have a look:

* MD5 sum did not patch, exiting https://github.com/babun/babun/issues/265[#265]
* Package 'git' is broken after update https://github.com/babun/babun/issues/259[#259]
* Cmake just returns to prompt without doing anything https://github.com/babun/babun/issues/252[#252]
* Upgrading Git https://github.com/babun/babun/issues/242[#242]
* versioning in pact, and pact upgrade & pact dist-upgrade (or the other way) https://github.com/babun/babun/issues/239[#239]
* Updating git https://github.com/babun/babun/issues/232[#232]
* Numpy not working after pact install https://github.com/babun/babun/issues/231[#231]
* Command exits with 127 on Babun, but works on Cygwin https://github.com/babun/babun/issues/225[#225]
* Unable to start X server after pact install xorg-server xinit https://github.com/babun/babun/issues/222[#222]
* Emacs doesn't run https://github.com/babun/babun/issues/210[#210]
* g++ compilation doesn't produce any resulting file https://github.com/babun/babun/issues/203[#203]
* Upgrading with pact not available https://github.com/babun/babun/issues/199[#199]
* shellshock: bash 4.1.10(4) and zsh 5.0.2 (i686-cygwin) vulnerablility https://github.com/babun/babun/issues/198[#198]
* Pact Installer, Md5 checksum not matching... https://github.com/babun/babun/issues/257[#257]
* Add "login" command to babun's script https://github.com/babun/babun/issues/253[#253]
* Rerun babun startup scripts after running 'babun update' https://github.com/babun/babun/issues/250[#250]
* Duplicate call of babun.zsh in /etc/zshrc https://github.com/babun/babun/issues/249[#249]
* Git plugin changes my gitconfig https://github.com/babun/babun/issues/247[#247]
* Cannot update oh-my-zsh on start https://github.com/babun/babun/issues/211[#211]
* etc/zprofile is being called twice causing CHERE_INVOKING to fail. https://github.com/babun/babun/issues/205[#205]
* `.bashrc` running three times https://github.com/babun/babun/issues/166[#166]
